### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'

### ISSUE THREAD

**Issue by tenseisoham** [pengzhiliang/MAE-pytorch#102]
Traceback (most recent call last):
  File "D:\sem6\MAE-pytorch\run_mae_vis.py", line 141, in <module>
    main(opts)
  File "D:\sem6\MAE-pytorch\run_mae_vis.py", line 81, in main
    model = get_model(args)
  File "D:\sem6\MAE-pytorch\run_mae_vis.py", line 64, in get_model
    model = create_model(
  File "D:\anaconda\lib\site-packages\timm\models\_factory.py", line 117, in create_model
    model = create_fn(
  File "D:\sem6\MAE-pytorch\modeling_pretrain.py", line 306, in pretrain_mae_base_patch16_224
    model = PretrainVisionTransformer(
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'

**Comment by FVT34U** [comment]
same, have any ideas?

**Comment by Neicth** [comment]
how to solve?
