### ISSUE TITLE
Run with pretrain_mae_vit_base_mask_0.75_400e.pth get an model initialization error

### ISSUE THREAD

**Issue by Owen-Fish** [pengzhiliang/MAE-pytorch#15]
Traceback (most recent call last):
  File "run_mae_vis.py", line 138, in <module>
    main(opts)
  File "run_mae_vis.py", line 79, in main
    model = get_model(args)
  File "run_mae_vis.py", line 63, in get_model
    model = create_model(
  File "/home/ub/miniconda3/envs/torch1.8/lib/python3.6/site-packages/timm/models/factory.py", line 57, in create_model
    model = create_fn(**model_args, **kwargs)
  File "/home/ub/bwj/MAE-pytorch/modeling_pretrain.py", line 317, in pretrain_mae_base_patch16_224
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_classes'

**Comment by pengzhiliang** [comment]
OK, maybe you should run:
```bash
pip install timm==0.3.2
```
I've fixed it in `requirements.txt` in latest commit.

**Comment by zongzi13545329** [comment]
I have installed timm==0.3.2 mentioned above but still, have the same error.

**Comment by pengzhiliang** [comment]
Emm, ok. 
I've add the unused keyword argument `num_classes` in `PretrainVisionTransformer`

**Comment by Owen-Fish** [comment]
OK bug fixed. that's a lot!
