### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by cuge1995** [pengzhiliang/MAE-pytorch#2]
```
MAE-pytorch/modeling_pretrain.py", line 296, in pretrain_mae_base_patch16_224
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_classes'
```

**Comment by pengzhiliang** [comment]
I'm sorry that I can't reproduce the bug you mentioned with the unmodified code in this repo. Can you provide more information?

**Comment by cuge1995** [comment]
just clone your repo, and follow the running code
```
# Set the path to save checkpoints
OUTPUT_DIR='output/'
# path to imagenet-1k train set
DATA_PATH='../ImageNet_ILSVRC2012/train'


OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=8 run_mae_pretraining.py \
        --data_path ${DATA_PATH} \
        --mask_ratio 0.75 \
        --model pretrain_mae_base_patch16_224 \
        --batch_size 128 \
        --opt_betas 0.9 0.95 \
        --warmup_epochs 40 \
        --epochs 1600 \
        --output_dir ${OUTPUT_DIR}
```

**Comment by cuge1995** [comment]
more logs are as follows:
```
Creating model: pretrain_mae_base_patch16_224
Traceback (most recent call last):
  File "run_mae_pretraining.py", line 264, in <module>
    main(opts)
  File "run_mae_pretraining.py", line 150, in main
    model = get_model(args)
  File "run_mae_pretraining.py", line 129, in get_model
    drop_block_rate=None,
  File "timm/models/factory.py", line 57, in create_model
    model = create_fn(**model_args, **kwargs)
  File "/home/ssd/zjl/zjl/unsupervised/MAE-pytorch/modeling_pretrain.py", line 296, in pretrain_mae_base_patch16_224
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_classes'
Traceback (most recent call last):
```

**Comment by PhoneSix** [comment]
I can run it successfully. Maybe you can check the version of timm.

**Comment by launchauto** [comment]
> ```
> MAE-pytorch/modeling_pretrain.py", line 296, in pretrain_mae_base_patch16_224
>     **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'num_classes'
> ```

pip install timm==0.3.2 will help

**Comment by shandong-university-weihai-chen** [comment]
> MAE-pytorch/modeling_pretrain.py", line 296, in pretrain_mae_base_patch16_224
>     **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'num_classes'

Have you solved this problem? I met it too

**Comment by pengzhiliang** [comment]
Hello, @shandong-university-weihai-chen . You can have a try:
```bash
pip install timm==0.3.2
```

**Comment by shandong-university-weihai-chen** [comment]
It’s very nice of you, I solve this problem by changing all ‘>=’ to ‘==’ in ‘requirements.txt’

**Comment by pengzhiliang** [comment]
You are welcome.
